import Head from 'next/head'
import Banner from './compnents/Banner/Banner'
import Aboutus from './compnents/Aboutus/Aboutus'
import Layout from './compnents/Layout/Layout'
import FeaturedProject from './compnents/FeaturedProject/FeaturedProject'
import OurServices from './compnents/OurServices/OurServices'
import DesignSolutions from './compnents/DesignSolutions/DesignSolutions'
import ScrollBrands from './compnents/Scroll/ScrollBrands'
import ScrollHeadings from './compnents/Scroll/ScrollHeadings'

const projectData = [
  {
    title: '712 Creative website',
    subtitle: 'Redesign & Development',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.',
    heading: 'Design & Development',
    // image1: '/assets/Portfolio1.jpeg',
    // image2: '/assets/Portfolio2.jpeg',
  },
  {
    title: 'Innovative Mobile Apps',
    subtitle: 'Redesign & Development',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.',
    heading: 'Mobile App Development',
    // image1: '/assets/Portfolio3.jpeg',
    // image2: '/assets/Portfolio4.jpeg',
  },
]

const Home =
  // : NextPage
  () => {
    return (
      <div>
        <Head>
          <title>Dipixels</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Layout>
          <Banner />
          <Aboutus />
          <FeaturedProject
            data={projectData}
            marqueeText='Featured Projects'
            heading={<h1>Featured Projects</h1>}
          />
          <OurServices />
          <DesignSolutions />
          <ScrollBrands />
          <ScrollHeadings /> 
        </Layout>
      </div>
    )
  }

export default Home
